In [79]:
# Importing
import tensorflow as tf
import pandas as pd
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np

In [80]:
# Understanding and manipulating data
data = pd.read_csv("titanic_data/train.csv")
train = data.copy()
labels = train.pop('Survived')
train.head()

PassengerId  Pclass                                               Name  \
0            1       3                            Braund, Mr. Owen Harris   
1            2       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2            3       3                             Heikkinen, Miss. Laina   
3            4       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4            5       3                           Allen, Mr. William Henry   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S  
1  female  38.0      1      0          PC 17599  71.2833   C85        C  
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
3  female  35.0      1      0            113803  53.1000  C123        S  
4    male  35.0      0      0            373450   8.0500   NaN        S

In [81]:
labels.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [82]:
CATEGORICAL_COLUMN = ["Name" , "Sex" , "Ticket","Cabin","Embarked"]
NUMERICAL_COLUMN = ["PassengerId" , "Pclass","Age","SibSp","Parch", "Fare"]
features_column = []
for col in CATEGORICAL_COLUMN :
    train.pop(str(col))
train

PassengerId  Pclass   Age  SibSp  Parch     Fare
0              1       3  22.0      1      0   7.2500
1              2       1  38.0      1      0  71.2833
2              3       3  26.0      0      0   7.9250
3              4       1  35.0      1      0  53.1000
4              5       3  35.0      0      0   8.0500
..           ...     ...   ...    ...    ...      ...
886          887       2  27.0      0      0  13.0000
887          888       1  19.0      0      0  30.0000
888          889       3   NaN      1      2  23.4500
889          890       1  26.0      0      0  30.0000
890          891       3  32.0      0      0   7.7500

[891 rows x 6 columns]

In [88]:
train.fillna(0) # Removing that unnecessary NaN and putting mean age there.

PassengerId  Pclass   Age  SibSp  Parch     Fare
0              1       3  22.0      1      0   7.2500
1              2       1  38.0      1      0  71.2833
2              3       3  26.0      0      0   7.9250
3              4       1  35.0      1      0  53.1000
4              5       3  35.0      0      0   8.0500
..           ...     ...   ...    ...    ...      ...
886          887       2  27.0      0      0  13.0000
887          888       1  19.0      0      0  30.0000
888          889       3   0.0      1      2  23.4500
889          890       1  26.0      0      0  30.0000
890          891       3  32.0      0      0   7.7500

[891 rows x 6 columns]

In [68]:
for feature_name in CATEGORICAL_COLUMN :
    vocab = train[feature_name].unique()
    features_column.append(tf.feature_column.categorical_column_with_vocabulary_list(feature_name,vocab))

for feature_name in NUMERICAL_COLUMN :
    features_column.append(tf.feature_column.numeric_column(feature_name, dtype=tf.float32))


In [89]:
train

PassengerId  Pclass   Age  SibSp  Parch     Fare
0              1       3  22.0      1      0   7.2500
1              2       1  38.0      1      0  71.2833
2              3       3  26.0      0      0   7.9250
3              4       1  35.0      1      0  53.1000
4              5       3  35.0      0      0   8.0500
..           ...     ...   ...    ...    ...      ...
886          887       2  27.0      0      0  13.0000
887          888       1  19.0      0      0  30.0000
888          889       3   NaN      1      2  23.4500
889          890       1  26.0      0      0  30.0000
890          891       3  32.0      0      0   7.7500

[891 rows x 6 columns]

In [90]:
train.shape , labels.shape

((891, 6), (891,))

In [91]:
train = train.to_numpy()
train

array([[  1.    ,   3.    ,  22.    ,   1.    ,   0.    ,   7.25  ],
       [  2.    ,   1.    ,  38.    ,   1.    ,   0.    ,  71.2833],
       [  3.    ,   3.    ,  26.    ,   0.    ,   0.    ,   7.925 ],
       ...,
       [889.    ,   3.    ,      nan,   1.    ,   2.    ,  23.45  ],
       [890.    ,   1.    ,  26.    ,   0.    ,   0.    ,  30.    ],
       [891.    ,   3.    ,  32.    ,   0.    ,   0.    ,   7.75  ]])

In [92]:
train.reshape(-1)

array([ 1.  ,  3.  , 22.  , ...,  0.  ,  0.  ,  7.75])

In [54]:
labels = labels.to_numpy()
labels

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [93]:
model = keras.Sequential([
    layers.Dense(512,activation='relu'), # 512 nodes and relu activation function used
    layers.Dense(256, activation='relu'),
    layers.Dense(10), # Output layer
])

In [94]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True), # it will sent softmax activation function.
    optimizer=keras.optimizers.Adam(lr=0.001),# learning rate =0.001 to avoid overfitting.
    metrics=['accuracy'],
)

c:\users\india\appdata\local\programs\python\python38\lib\site-packages\keras\optimizer_v2\adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


In [130]:
# training model
model.fit(train, labels, batch_size=32, epochs=1 , verbose=1)

28/28 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.6162


In [139]:
test_data = pd.read_csv("titanic_data/test.csv")
test_labels = pd.read_csv("titanic_data/gender_submission.csv")
test_labels.head()

PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1

In [140]:
x_test = test_data.copy()
for col in CATEGORICAL_COLUMN :
    x_test.pop(str(col))
x_test.fillna(0)
y_test = test_labels.copy()
y_test = y_test.pop('Survived')

In [141]:
x_test = x_test.to_numpy()
y_test = y_test.to_numpy()

In [142]:
x_test

array([[8.92000e+02, 3.00000e+00, 3.45000e+01, 0.00000e+00, 0.00000e+00,
        7.82920e+00],
       [8.93000e+02, 3.00000e+00, 4.70000e+01, 1.00000e+00, 0.00000e+00,
        7.00000e+00],
       [8.94000e+02, 2.00000e+00, 6.20000e+01, 0.00000e+00, 0.00000e+00,
        9.68750e+00],
       ...,
       [1.30700e+03, 3.00000e+00, 3.85000e+01, 0.00000e+00, 0.00000e+00,
        7.25000e+00],
       [1.30800e+03, 3.00000e+00,         nan, 0.00000e+00, 0.00000e+00,
        8.05000e+00],
       [1.30900e+03, 3.00000e+00,         nan, 1.00000e+00, 1.00000e+00,
        2.23583e+01]])

In [143]:
y_test

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [144]:
test = np.round(test, 2)
test

array([[8.920e+02, 3.000e+00, 3.450e+01, 0.000e+00, 0.000e+00, 7.830e+00],
       [8.930e+02, 3.000e+00, 4.700e+01, 1.000e+00, 0.000e+00, 7.000e+00],
       [8.940e+02, 2.000e+00, 6.200e+01, 0.000e+00, 0.000e+00, 9.690e+00],
       ...,
       [1.307e+03, 3.000e+00, 3.850e+01, 0.000e+00, 0.000e+00, 7.250e+00],
       [1.308e+03, 3.000e+00,       nan, 0.000e+00, 0.000e+00, 8.050e+00],
       [1.309e+03, 3.000e+00,       nan, 1.000e+00, 1.000e+00, 2.236e+01]])

In [153]:
loss,acc = model.evaluate(x_test, y_test,batch_size=32,verbose=2)
print(acc)

14/14 - 0s - loss: nan - accuracy: 0.6364 - 46ms/epoch - 3ms/step
0.6363636255264282


In [146]:
probability_model = tf.keras.Sequential([model, 
                                         tf.keras.layers.Softmax()])

In [156]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_9 (Dense)             (None, 512)               3584      
                                                                 
 dense_10 (Dense)            (None, 256)               131328    
                                                                 
 dense_11 (Dense)            (None, 10)                2570      
                                                                 
Total params: 137,482
Trainable params: 137,482
Non-trainable params: 0
_________________________________________________________________


In [154]:
# from keras.utils.vis_utils import plot_model  
# plot_model(model, show_shapes=True, show_layer_names=True)


You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model/model_to_dot to work.
